import { AlertTriangle, Info } from "lucide-react"
import { cn } from "@/lib/utils"

interface DisclaimerBannerProps {
  className?: string
  variant?: "info" | "warning"
}

export function DisclaimerBanner({ className, variant = "info" }: DisclaimerBannerProps) {
  if (variant === "warning") {
    return (
      <div className={cn(
        "flex items-start gap-3 rounded-lg border border-amber-500/30 bg-amber-500/10 p-4",
        className
      )}>
        <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-500 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-sm font-medium text-amber-800 dark:text-amber-400">
            AI-Assisted Analysis — Not Authoritative
          </p>
          <p className="text-sm text-amber-700 dark:text-amber-500/90 leading-relaxed">
            Results are generated by AI and may contain errors. This tool is for informational purposes only
            and should not be cited as a definitive source. Always verify claims through official fact-checking
            organizations before sharing.
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className={cn(
      "flex items-start gap-3 rounded-lg border border-muted bg-muted/30 p-4",
      className
    )}>
      <Info className="w-5 h-5 text-muted-foreground shrink-0 mt-0.5" />
      <p className="text-sm text-muted-foreground leading-relaxed">
        This analysis is probabilistic, not definitive. Use as a starting point, not the final word.
        Verity helps you see what can be verified—the rest is up to your judgment.
      </p>
    </div>
  )
}
